catch(...)
{
  cerr<<"Receiver function died with unknown exception"<<endl;
  exit(1);
}